import Head from "next/head"
import Footer from "./Footer"
import Navbar from "./Navbar"

function Layout(props) {
  return (
    <>
      <Head>
        <title>Fitnessworks{props.title ? ' - ' + props.title : ''}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main>{ props.children }</main>
      <Footer/>
    </>
  )
}

export default Layout